export const sections = [
  {id:'atrio',title:'El atrio',ids:['atrio','altar','mar','fuentes']},
  {id:'portico',title:'El umbral',ids:['portico','jaquin','boaz']},
  {id:'hekal',title:'Hekal · Lugar Santo',ids:['hekal','puertas','candelabros','mesas','incienso']},
  {id:'debir',title:'Debir · Santísimo',ids:['debir','velo','arca','querubines']},
  {id:'estructura',title:'La arquitectura',ids:['camaras','muros','techo','ventanas']},
];
const item=(id,name,zone,ref,summary,detail,observe,material,size,point,view)=>({id,name,zone,ref,summary,detail,observe,material,size,point,view});
export const elements=[
  item('atrio','Atrio de los sacerdotes','atrio','1 Reyes 6:36; 2 Crónicas 4:9','Un espacio abierto ante la casa.','Los relatos distinguen un atrio interior y un atrio mayor. Aquí se reúnen el altar y los recipientes para el lavado. El trazado del recinto, su pavimento y sus accesos son ilustrativos: no se ofrece un plano completo con medidas.','Sigue el eje desde la entrada hasta el pórtico.','Piedra, cedro y bronce','Perímetro ilustrativo',[0,.8,18],[43,32,55]),
  item('altar','Altar de los holocaustos','atrio','2 Crónicas 4:1','Un gran altar revestido de bronce.','Crónicas describe un altar de veinte codos por lado y diez de altura. Su escala es mucho mayor que la del altar portátil del tabernáculo. Los detalles superiores de esta reconstrucción son esquemáticos.','Compara su altura con la de una persona al caminar.','Bronce','20 × 20 × 10 codos',[0,3,24],[15,12,39]),
  item('mar','El mar de bronce','atrio','1 Reyes 7:23–26; 2 Crónicas 4:2–6, 10','Una gran pila sobre doce bueyes.','El recipiente circular se situaba al sureste. Los bueyes se organizaban en cuatro grupos de tres, orientados hacia los puntos cardinales. Crónicas asocia el mar al lavado sacerdotal. Reyes indica 2.000 batos y Crónicas 3.000; aquí se conserva esa diferencia sin imponer una explicación.','Cuenta los doce bueyes y observa el borde en forma de flor.','Bronce y agua','10 codos de diámetro; 5 de altura del recipiente',[12,3,16],[21,9,24]),
  item('fuentes','Las diez fuentes móviles','atrio','1 Reyes 7:27–39; 2 Crónicas 4:6','Recipientes sobre bases con ruedas.','Cinco fuentes se colocaban a cada lado. Las bases tenían paneles decorados y ruedas; las fuentes servían para lavar lo destinado al holocausto. Se distinguen del mar usado por los sacerdotes.','Localiza las cinco bases al norte y las cinco al sur.','Bronce','10 fuentes · bases de 4 × 4 × 3 codos',[16,1.7,5],[25,10,13]),
  item('portico','Ulam · el pórtico','portico','1 Reyes 6:3; 2 Crónicas 3:4','El vestíbulo que precedía a la nave.','El ancho del pórtico coincidía con el de la casa y su profundidad era diez codos. Su altura presenta una dificultad textual: algunas versiones de Crónicas dicen 120 codos y otras 20. La elevación de esta fachada es una propuesta visual, no una medida resuelta.','Sube por la escalinata ilustrativa y cruza el espacio entre las columnas.','Piedra y madera revestida','20 × 10 codos en planta',[0,5,8],[22,19,33]),
  item('jaquin','Jaquín','portico','1 Reyes 7:15–22','Una de las dos columnas de bronce.','Reyes atribuye dieciocho codos al fuste y cinco al capitel. Las redes, cadenas y granadas decoraban los capiteles. La posición de Jaquín sigue la lectura del lado derecho desde la casa hacia el este.','Mira hacia arriba para descubrir las granadas y el remate floral.','Bronce','18 codos + capitel de 5 codos',[3.5,7,9],[12,11,19]),
  item('boaz','Boaz','portico','1 Reyes 7:15–22; 2 Crónicas 3:15–17','La columna que acompaña a Jaquín.','Ambas columnas recibieron nombres propios. La representación sigue las dimensiones de Reyes; Crónicas presenta otra cifra para su altura. No se reproduce aquí una columna griega: el remate floral y las redes proceden del lenguaje del relato.','Compara los dos capiteles y localiza las franjas de granadas.','Bronce','Dimensiones según 1 Reyes 7',[-3.5,7,9],[-12,11,19]),
  item('hekal','Hekal · Lugar Santo','hekal','1 Reyes 6:17–22; 7:48–49','La gran nave de servicio sacerdotal.','La sala anterior medía cuarenta codos de longitud. El revestimiento de cedro tallado y oro ocultaba la piedra. Los muebles se distribuyen a ambos lados, dejando un eje de paso hacia el recinto interior.','Observa las palmeras, las flores y la sucesión de luces.','Cedro, oro y madera de suelo','40 × 20 codos en planta',[0,4,-5],[15,20,10]),
  item('puertas','Puertas talladas','hekal','1 Reyes 6:31–35','Hojas de madera, relieves y oro.','El relato describe puertas de madera de olivo para el recinto interior y hojas de madera de ciprés para la entrada de la nave, con tallas de querubines, palmeras y flores. Aquí las hojas se abren al entrar en modo caminata.','Distingue la puerta exterior del cierre del Debir.','Maderas talladas y oro','Detalles y mecanismos ilustrativos',[0,4,5],[9,7,14]),
  item('candelabros','Diez candelabros de oro','hekal','1 Reyes 7:49; 2 Crónicas 4:7','Cinco luminarias a cada lado.','Los textos enumeran diez candelabros. La forma de siete brazos mostrada aquí es una interpretación por continuidad con la menorá del tabernáculo; no es una descripción detallada de estas piezas en Reyes.','Cuenta cinco a la derecha y cinco a la izquierda.','Oro','10 candelabros',[3.5,2.6,-5],[0,5,1]),
  item('mesas','Mesas del pan de la Presencia','hekal','1 Reyes 7:48; 2 Crónicas 4:8, 19','El pan dispuesto ante Dios.','Reyes menciona la mesa de oro; Crónicas enumera diez mesas, cinco a cada lado. Este modelo adopta esa disposición. Sus dimensiones y la forma de los utensilios son ilustrativas; no se trasladan como obligatorias las medidas de la mesa portátil.','Distingue las mesas de los candelabros entre ellas.','Oro y madera · pan ilustrativo','10 mesas según Crónicas',[-3.5,2,-6.7],[0,4,-2]),
  item('incienso','Altar del incienso','hekal','1 Reyes 6:20–22; 7:48','Un altar de oro delante del recinto interior.','Reyes menciona el altar revestido de oro relacionado con el santuario interior. Su tamaño en el templo no se precisa en estos pasajes; el modelo destaca su posición y su función sin asignarle las medidas del altar del tabernáculo.','Sigue el humo hasta las puertas y el velo del Debir.','Madera y oro','Medidas ilustrativas',[0,2.3,-11.5],[4,4,-7]),
  item('debir','Debir · Lugar Santísimo','debir','1 Reyes 6:16, 19–28; 8:6','Un recinto cúbico dentro de la casa.','El recinto interior medía veinte codos en cada dimensión. Allí se situó el arca bajo las alas de los grandes querubines. La visita libre es un recurso educativo, distinto del acceso sacerdotal regulado.','Compara los diez metros convencionales de ancho, fondo y alto.','Cedro recubierto de oro','20 × 20 × 20 codos',[0,4,-20],[14,18,-10]),
  item('velo','El velo del santuario','debir','2 Crónicas 3:14','Tejido bordado ante el recinto interior.','Crónicas añade un velo de lino con azul, púrpura y carmesí, bordado con querubines. El modelo presenta tanto las puertas descritas por Reyes como el velo citado en Crónicas; su relación espacial exacta es una decisión de reconstrucción.','Observa el tejido detrás de las puertas talladas.','Lino bordado','Colocación y dibujo ilustrativos',[0,5,-15.3],[5,6,-10]),
  item('arca','Arca del pacto','debir','1 Reyes 8:6–9; Éxodo 25:10–22','El arca trasladada al nuevo santuario.','Los sacerdotes colocaron el arca debajo de las alas de los querubines. Reyes precisa que en ese momento contenía las dos tablas de piedra. Se representa el cofre conocido por Éxodo, con sus varas y cubierta; las figuras pequeñas no deben confundirse con los grandes querubines de Salomón.','Compara el arca con las figuras de cinco metros a sus lados.','Acacia y oro','2,5 × 1,5 × 1,5 codos, según Éxodo',[0,2,-20],[3,4,-16]),
  item('querubines','Los grandes querubines','debir','1 Reyes 6:23–28; 2 Crónicas 3:10–13','Dos figuras cuyas alas abarcaban la sala.','Cada querubín medía diez codos de alto y diez de envergadura. Sus alas exteriores alcanzaban las paredes, mientras las interiores se tocaban. Se tallaron en madera de olivo y se recubrieron de oro. El aspecto de los cuerpos es artístico.','Sigue las alas de pared a pared; debajo se encuentra el arca.','Madera de olivo y oro','10 codos de alto por figura',[0,5,-20],[0,7,-13]),
  item('camaras','Cámaras laterales','estructura','1 Reyes 6:5–10','Tres niveles junto a los muros.','La casa tenía dependencias laterales. Sus anchuras aumentaban de cinco a seis y siete codos gracias a los retranqueos del muro. El acceso, las particiones y las escaleras no se reconstruyen aquí con exactitud: los volúmenes permiten estudiar su disposición exterior.','Levanta los techos para distinguir los tres niveles.','Piedra, vigas y cedro','Tres niveles; 5, 6 y 7 codos de ancho',[7.5,5,-6],[24,15,14]),
  item('muros','Piedra, cedro y oro','estructura','1 Reyes 6:7, 15–22, 29–30','Una arquitectura de materiales superpuestos.','Las piedras llegaban preparadas desde la cantera. El interior revestido de madera estaba decorado con figuras vegetales y querubines, y cubierto de oro. La trama de los bloques y los relieves de esta propuesta son ilustrativos.','Abre el edificio para contrastar la piedra exterior con el oro interior.','Piedra labrada, cedro y oro','Casa: 60 × 20 × 30 codos',[5.5,9,-6],[24,18,6]),
  item('techo','Vigas y cubiertas','estructura','1 Reyes 6:9–10','Cedro por encima de las estancias.','La casa se cubría con vigas y tablas de cedro. Aquí se muestran techos planos y una disposición esquemática de vigas. El botón de levantamiento separa las cubiertas para estudiar la nave, el Debir y las dependencias.','Pulsa «Levantar techos» y mira el edificio desde arriba.','Vigas y tablazón de cedro','Despiece ilustrativo',[0,16.5,-9],[30,30,25]),
  item('ventanas','Ventanas altas','estructura','1 Reyes 6:4','Aberturas en la parte superior de los muros.','Las traducciones describen ventanas con marcos o celosías. Su número y su forma exacta no quedan definidos. La serie de aberturas altas y las celosías de este modelo son una solución visual para comprender la iluminación de la nave.','Busca las aberturas por encima de las cámaras laterales.','Piedra y celosías de madera','Número y diseño ilustrativos',[5.5,12,-5],[17,15,6]),
];
export const byId=Object.fromEntries(elements.map(e=>[e.id,e]));
export function resolvePart(value){
  const aliases={'court-inner':'atrio','court-great':'atrio',gates:'portico',ulam:'portico',pillars:'jaquin',sea:'mar',lavers:'fuentes',menorot:'candelabros',table:'mesas',incense:'incienso',ark:'arca',cherubim:'querubines',veil:'velo',chambers:'camaras',temple:'muros','temple-roof':'techo'};
  const id=Object.hasOwn(aliases,value)?aliases[value]:value;return Object.hasOwn(byId,id)?id:null;
}
export const tour=['atrio','altar','mar','fuentes','portico','jaquin','boaz','puertas','hekal','candelabros','mesas','incienso','velo','debir','querubines','arca','camaras','techo'];
export const questions=[
  {q:'¿Cómo se llamaban las dos columnas del pórtico?',answers:['Jaquín y Boaz','Moisés y Aarón','Hekal y Debir'],correct:0,why:'1 Reyes 7:21 da los nombres Jaquín y Boaz a las columnas.',id:'jaquin'},
  {q:'¿Cuántos bueyes sostenían el mar de bronce?',answers:['Diez','Doce','Siete'],correct:1,why:'Había cuatro grupos de tres bueyes, orientados hacia los cuatro puntos cardinales (1 Reyes 7:25).',id:'mar'},
  {q:'¿Cuál era la forma del Debir según sus medidas?',answers:['Circular','Triangular','Cúbica'],correct:2,why:'Medía veinte codos de largo, ancho y alto (1 Reyes 6:20).',id:'debir'},
  {q:'¿Cuántos candelabros había en el templo?',answers:['Diez, cinco a cada lado','Uno solo','Doce en círculo'],correct:0,why:'1 Reyes 7:49 enumera cinco a la derecha y cinco a la izquierda.',id:'candelabros'},
  {q:'¿Qué había en el arca al ser colocada en el templo?',answers:['Las herramientas del constructor','Las coronas de los reyes','Las dos tablas de piedra'],correct:2,why:'1 Reyes 8:9 identifica las dos tablas de piedra como su contenido en ese momento.',id:'arca'},
  {q:'¿Qué detalle de esta reconstrucción es ilustrativo?',answers:['Los nombres de las columnas','El trazado completo del atrio','La existencia del mar de bronce'],correct:1,why:'Los relatos describen atrios, pero no ofrecen un plano completo con todas sus medidas.',id:'atrio'},
];
export function scriptureUrl(ref){return `https://www.biblegateway.com/passage/?search=${encodeURIComponent(ref.replaceAll('–','-'))}&version=RVR1960`;}
