// Los textos son resúmenes didácticos originales, no transcripciones bíblicas.
export const sections = [
  { id: 'atrio', title: 'El atrio', subtitle: 'El primer encuentro', ids: ['atrio', 'puerta', 'columnas', 'altar', 'fuente', 'utensilios'] },
  { id: 'santo', title: 'El Lugar Santo', subtitle: 'Luz, pan e incienso', ids: ['santo', 'menora', 'mesa', 'incienso', 'entrada'] },
  { id: 'santisimo', title: 'El Lugar Santísimo', subtitle: 'Detrás del velo', ids: ['santisimo', 'velo', 'arca', 'propiciatorio'] },
  { id: 'estructura', title: 'La estructura', subtitle: 'Un santuario transportable', ids: ['tablas', 'barras', 'cubiertas'] },
];

const item = (id, name, zone, ref, summary, detail, observe, material, size, point, view) => ({ id, name, zone, ref, summary, detail, observe, material, size, point, view });
export const elements = [
  item('atrio', 'El atrio', 'atrio', 'Éxodo 27:9–19', 'El recinto abierto que rodeaba la tienda.', 'Las cortinas delimitaban un espacio apartado dentro del campamento. Aquí estaban el altar de los sacrificios y la fuente para el lavado sacerdotal.', 'Compara el espacio al aire libre con las dos habitaciones de la tienda.', 'Lino, bronce y plata', '100 × 50 codos', [0, 1, 4], [29, 26, 39]),
  item('puerta', 'La puerta del atrio', 'atrio', 'Éxodo 27:16', 'La entrada orientada hacia el este.', 'Una cortina de veinte codos, sostenida por cuatro columnas, marcaba el acceso. Su bordado reunía azul, púrpura, carmesí y lino.', 'Localiza la puerta en el mapa y sigue el camino hacia el santuario.', 'Lino bordado', '20 codos de ancho', [0, 1.5, 25], [9, 5, 33]),
  item('columnas', 'Columnas y estacas', 'atrio', 'Éxodo 27:10–19', 'El soporte del perímetro de lino.', 'El texto describe basas de bronce, ganchos y uniones de plata. Las cuerdas y estacas estabilizan las cortinas en esta representación; el material del cuerpo de los postes no se especifica aquí.', 'Busca las bases, los remates y las cuerdas junto a las cortinas.', 'Basas de bronce · herrajes de plata', '5 codos de altura del cerco', [12.5, 1.7, 12.5], [18, 4, 17]),
  item('altar', 'Altar del holocausto', 'atrio', 'Éxodo 27:1–8', 'El altar de bronce para las ofrendas.', 'Se construía en acacia revestida de bronce, con cuatro cuernos, rejilla y varas para transportarlo. Su posición en el atrio permitía el servicio de los sacrificios.', 'Cuenta los cuatro cuernos y distingue la rejilla de las varas.', 'Acacia y bronce', '5 × 5 × 3 codos', [0, 1, 14], [4.8, 3.8, 19]),
  item('fuente', 'Fuente de bronce', 'atrio', 'Éxodo 30:17–21', 'Agua para el lavado de manos y pies.', 'Se colocaba entre la tienda y el altar. Aarón y sus hijos debían lavarse antes de entrar a servir o de acercarse al altar. El pasaje no especifica sus dimensiones ni su forma exacta.', 'Observa su lugar en el camino entre el altar y la tienda.', 'Bronce y agua', 'Medidas no especificadas', [0, 0.8, 6], [3, 2.5, 9.2]),
  item('utensilios', 'Utensilios del altar', 'atrio', 'Éxodo 27:3', 'Instrumentos para el servicio del altar.', 'Se mencionan recipientes para cenizas, palas, tazones, garfios y braseros. Las formas de estas piezas son ilustrativas y ayudan a distinguir sus funciones.', 'Encuentra el recipiente, la pala y el garfio al lado del altar.', 'Bronce', 'Formas ilustrativas', [3.5, 0.4, 14], [5.8, 2.1, 17]),
  item('santo', 'El Lugar Santo', 'santo', 'Éxodo 26:33–35', 'La primera estancia de la tienda.', 'Aquí se disponían la mesa al norte, el candelero al sur y el altar de incienso delante del velo. Era el espacio de servicio de los sacerdotes.', 'Ubica los tres muebles y compáralos con el plano.', 'Tablas de oro y cortinas de lino', '20 × 10 codos, reconstrucción habitual', [0, 1, -7], [7, 9, 2]),
  item('menora', 'Candelero de oro', 'santo', 'Éxodo 25:31–40', 'Siete lámparas iluminaban el Lugar Santo.', 'El candelero se describe como una pieza de oro labrado, con un eje central, seis brazos y adornos semejantes a flores de almendro. Sus lámparas usaban aceite.', 'Cuenta las siete lámparas: una central y tres a cada lado.', 'Oro', 'Un talento; altura no especificada', [1.55, 1.1, -7], [0, 2.1, -4.5]),
  item('mesa', 'Mesa de los panes', 'santo', 'Éxodo 25:23–30; Levítico 24:5–9', 'Doce panes colocados ante Dios.', 'La mesa de acacia revestida de oro llevaba una moldura y varas de transporte. Levítico prescribe doce panes, ordenados en dos grupos de seis y renovados cada sábado.', 'Cuenta los dos grupos de seis panes sobre la mesa.', 'Acacia, oro y pan', '2 × 1 × 1,5 codos', [-1.5, 0.9, -7], [0.4, 2, -4.8]),
  item('incienso', 'Altar del incienso', 'santo', 'Éxodo 30:1–10', 'El altar dorado situado ante el velo.', 'Era más pequeño que el altar exterior. Tenía cuernos y una moldura de oro. Aarón debía quemar incienso aromático al preparar las lámparas por la mañana y al atardecer.', 'Compara su tamaño y su material con el altar del atrio.', 'Acacia y oro', '1 × 1 × 2 codos', [0, 0.8, -11], [1.8, 2.2, -8.5]),
  item('entrada', 'Entrada de la tienda', 'santo', 'Éxodo 26:36–37', 'Una cortina entre el atrio y el santuario.', 'Cinco columnas de acacia recubiertas de oro, asentadas en basas de bronce, sostenían la cortina bordada. No es el mismo velo que divide las dos habitaciones interiores.', 'Distingue las cinco columnas de esta entrada de las cuatro del velo.', 'Lino, acacia, oro y bronce', '5 columnas', [0, 2.5, -2.5], [7, 5, 3]),
  item('santisimo', 'El Lugar Santísimo', 'santisimo', 'Éxodo 26:33–34; Levítico 16', 'La estancia más interior del santuario.', 'Detrás del velo estaban el arca y su cubierta. El acceso ritual del sumo sacerdote correspondía al Día de la Expiación, con las condiciones descritas en Levítico 16. Aquí puedes entrar con fines educativos.', 'Observa cómo el velo separa este espacio del Lugar Santo.', 'Oro y lino bordado', '10 × 10 × 10 codos, reconstrucción habitual', [0, 1, -15], [6, 8, -10]),
  item('velo', 'El velo', 'santisimo', 'Éxodo 26:31–33', 'La separación entre los dos espacios santos.', 'El velo de lino con azul, púrpura y carmesí llevaba figuras de querubines. Cuatro columnas revestidas de oro con basas de plata lo sostenían.', 'Compara sus querubines con los de la cubierta del arca.', 'Lino bordado · oro · plata', '4 columnas', [0, 2, -12.5], [3.5, 3, -9]),
  item('arca', 'Arca del pacto', 'santisimo', 'Éxodo 25:10–16', 'El cofre que guardaba el testimonio.', 'La madera de acacia estaba recubierta de oro por dentro y por fuera. Cuatro argollas sostenían las varas, que debían permanecer en ellas. En el cofre se depositaban las tablas del testimonio.', 'Busca las argollas, las dos varas y la moldura superior.', 'Acacia revestida de oro', '2,5 × 1,5 × 1,5 codos', [0, 0.75, -15], [2.6, 2.1, -12.8]),
  item('propiciatorio', 'Propiciatorio y querubines', 'santisimo', 'Éxodo 25:17–22', 'La cubierta de oro sobre el arca.', 'Dos querubines se orientaban uno hacia el otro, con las alas extendidas por encima de la cubierta. Desde allí Dios prometió comunicar sus instrucciones a Moisés. La forma de las figuras es una interpretación artística.', 'Observa la cubierta y la dirección de las alas.', 'Oro', '2,5 × 1,5 codos', [0, 1.2, -15], [1.8, 1.9, -13.1]),
  item('tablas', 'Tablas y basas', 'estructura', 'Éxodo 26:15–25, 29', 'Una estructura que podía desmontarse.', 'Tablas de acacia revestidas de oro se apoyaban en basas de plata. El texto prescribe veinte tablas por cada lado largo y seis más dos de esquina en la parte posterior.', 'Usa «Ver interior» para distinguir las tablas del revestimiento.', 'Acacia, oro y plata', '10 × 1,5 codos por tabla', [2.5, 2.5, -8], [10, 6, -3]),
  item('barras', 'Barras de unión', 'estructura', 'Éxodo 26:26–29', 'Los travesaños que unían las tablas.', 'Cinco barras por cada lado de la estructura daban estabilidad a la tienda. La barra central recorría las tablas de extremo a extremo. Se recubrían de oro y pasaban por argollas.', 'Sigue los travesaños horizontales a lo largo de una pared.', 'Acacia revestida de oro', '5 barras por lado', [2.8, 2.5, -8], [8, 4.5, -4]),
  item('cubiertas', 'Las cuatro cubiertas', 'estructura', 'Éxodo 26:1–14', 'Tejidos y pieles protegían la tienda.', 'De dentro hacia fuera: lino bordado, pelo de cabra, pieles de carnero teñidas de rojo y una cubierta exterior de pieles. La identificación del término hebreo tajash varía entre traducciones.', 'Pulsa «Separar cubiertas» para ver las cuatro capas por separado.', 'Lino · pelo de cabra · pieles', '4 capas ilustradas', [0, 5.4, -10], [16, 14, 4]),
];
export const byId = Object.fromEntries(elements.map(e => [e.id, e]));
export function resolvePart(value) {
  const legacy = { 'puerta-atrio': 'puerta', tienda: 'cubiertas', 'lugar-santo': 'santo', candelero: 'menora', incensario: 'incienso', 'lugar-santisimo': 'santisimo', pantalla: 'entrada' };
  const id = Object.hasOwn(legacy, value) ? legacy[value] : value;
  return Object.hasOwn(byId, id) ? id : null;
}
export const tour = ['puerta', 'atrio', 'altar', 'fuente', 'entrada', 'santo', 'menora', 'mesa', 'incienso', 'velo', 'arca', 'propiciatorio', 'cubiertas'];
export const questions = [
  { q: '¿Hacia qué punto cardinal estaba la entrada del atrio?', answers: ['Este', 'Norte', 'Oeste'], correct: 0, why: 'Éxodo 27:13–16 sitúa el acceso en el lado oriental del atrio.', id: 'puerta' },
  { q: '¿Para qué se utilizaba la fuente de bronce?', answers: ['Guardar el incienso', 'Lavar manos y pies antes del servicio', 'Colocar los panes'], correct: 1, why: 'Éxodo 30:17–21 describe el lavado de Aarón y sus hijos antes del servicio.', id: 'fuente' },
  { q: '¿Cuántas lámparas tenía el candelero?', answers: ['Doce', 'Cinco', 'Siete'], correct: 2, why: 'El eje central y los seis brazos sostienen siete lámparas (Éxodo 25:31–37).', id: 'menora' },
  { q: '¿Qué separaba el Lugar Santo del Lugar Santísimo?', answers: ['El velo', 'La puerta del atrio', 'La fuente'], correct: 0, why: 'El velo divide los dos espacios interiores de la tienda (Éxodo 26:33).', id: 'velo' },
  { q: '¿Qué objeto se encontraba en el Lugar Santísimo?', answers: ['El altar de bronce', 'La mesa de los panes', 'El arca del pacto'], correct: 2, why: 'El arca, con el propiciatorio encima, se ubicaba detrás del velo (Éxodo 26:33–34).', id: 'arca' },
];
export function scriptureUrl(ref) {
  return `https://www.biblegateway.com/passage/?search=${encodeURIComponent(ref.replaceAll('–', '-'))}&version=RVR1960`;
}
